[deps]
ipython = ""
matplotlib = ""
imageio = ""
f90nml = ""
plotly = ""
seaborn = ""
cmake = ""
tqdm = ""
pandas = ""
dask = ""
numba = ""
astropy = ""
numpy = ""
scipy = ""
requests = ""

[pip.deps]
ipyformkit = ""
idlsave = ""
